apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: "hello-world"
spec:
  releaseName: "hello-world"
  timeout: 300
  resetValues: true
  forceUpgrade: false
  rollback:
    enable: false
  chart:
    git: git@github.com:tarungoel1995/helloworld
    ref: acc53fd1e42aa4181a4378e20e89fe74a1b01e65
    path: helloworld
#  values:
#    version: ""
#  valuesFrom:
#    - configMapKeyRef:
#        name: cluster-values
#        key: values